### PR TITLE
Change docker compose yml and other settings

### PR DESCRIPTION
**Pull request by thomas-maschler**
Make it work

### CODE REVIEW

**Comment by thomas-maschler** [comment]
You will need to delete the local gfw-area mongo database.
Go to ~/docker/data and delete it here

**Comment by thomas-maschler** [comment]
It seems like mongo isn't ready when express tries to connect. Tried to follow instructions from here
https://dev.to/hugodias/wait-for-mongodb-to-start-on-docker-3h8b

Need to check, if changes to dockerfile will impact production!
Also, this still doesn't work reliable for me locally

**Comment by edbrett** [comment]
Is this good to go? Can I merge?

**Comment by edbrett** [comment]
ok igtm.

**Pull request merged**
